// Ollama runtime manager
const { spawn } = require('child_process');
const DEFAULT_MODEL = 'qwen3:1.7b';
const BASE = 'http://127.0.0.1:11434';
function exists(cmd){return new Promise(resolve=>{const p=spawn(process.platform==='win32'?'where':'which',[cmd],{windowsHide:true});p.on('close',c=>resolve(c===0));p.on('error',()=>resolve(false));});}
function run(cmd,args,onLine=()=>{}){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:['ignore','pipe','pipe'],windowsHide:true});let out='';const f=x=>{const s=String(x);out+=s;s.split(/\r?\n/).filter(Boolean).forEach(onLine)};p.stdout.on('data',f);p.stderr.on('data',f);p.on('error',reject);p.on('close',c=>c===0?resolve(out):reject(new Error(out.trim()||cmd+' failed')));});}
async function status(){const installed=await exists('ollama');if(!installed)return{installed:false,running:false,models:[],version:null};let version=null,models=[];try{version=(await run('ollama',['--version'])).trim()}catch{}try{models=(await run('ollama',['list'])).split(/\r?\n/).slice(1).map(x=>x.trim().split(/\s+/)[0]).filter(Boolean)}catch{}let running=false;try{running=(await fetch(BASE+'/api/tags')).ok}catch{}return{installed:true,running,models,version};}
async function install(onLine=()=>{}){if(await exists('ollama'))return{ok:true,...await status()};if(process.platform==='win32'){onLine('Installing Ollama with winget...');await run('winget',['install','--id','Ollama.Ollama','--exact','--accept-package-agreements','--accept-source-agreements'],onLine)}else if(process.platform==='linux'){onLine('Installing Ollama from official installer...');await run('sh',['-c','curl -fsSL https://ollama.com/install.sh | sh'],onLine)}else throw new Error('Tự động cài Ollama hiện chỉ hỗ trợ Windows/Linux.');return{ok:true,...await status()};}
async function pullModel(model=DEFAULT_MODEL,onLine=()=>{}){if(!(await exists('ollama')))throw new Error('Ollama chưa được cài');const name=String(model).trim();if(!name)throw new Error('Tên model không được để trống');await run('ollama',['pull',name],onLine);return{ok:true,model:name,...await status()};}
async function removeModel(model,onLine=()=>{}){if(!(await exists('ollama')))throw new Error('Ollama chưa được cài');const name=String(model).trim();if(!name)throw new Error('Tên model không được để trống');await run('ollama',['rm',name],onLine);return{ok:true,...await status()};}
module.exports={DEFAULT_MODEL,status,install,pullModel,removeModel};