const express = require('express');
const path = require('path');
const { loadAccounts, saveAccounts, loadMessages, saveMessages, getPublicAccounts } = require('./config-store');
const config = require('../config');
const { aiListener } = require('./ai/ai-listener');
const { scheduler } = require('./automation-core');

const app = express();
app.use(express.json({ limit: '64kb' }));
app.get('/', (req, res) => res.sendFile(path.join(__dirname, '..', 'web', 'index.html')));
app.get('/api/config', (req, res) => res.json({...getPublicAccounts(),messages:loadMessages(),ai:aiListener.getStatus(),scheduler:scheduler.getStatus()}));

app.post('/api/accounts',(req,res)=>{const{id,name,token}=req.body||{};if(!id||!name||!token)return res.status(400).json({ok:false,error:'id, name và token là bắt buộc'});const d=loadAccounts();if(d.accounts.some(a=>a.id===id))return res.status(409).json({ok:false,error:'Account ID đã tồn tại'});d.accounts.push({id,name,token,channels:[]});if(!d.activeAccountId)d.activeAccountId=id;saveAccounts(d);res.status(201).json({ok:true,accounts:getPublicAccounts()})});
app.delete('/api/accounts/:id',(req,res)=>{const d=loadAccounts(),n=d.accounts.length;d.accounts=d.accounts.filter(a=>a.id!==req.params.id);if(d.accounts.length===n)return res.status(404).json({ok:false,error:'Account không tồn tại'});if(d.activeAccountId===req.params.id)d.activeAccountId=d.accounts[0]?.id||null;saveAccounts(d);res.json({ok:true,accounts:getPublicAccounts()})});
app.post('/api/accounts/:id/channels',(req,res)=>{const{channelId,name}=req.body||{},d=loadAccounts(),a=d.accounts.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({ok:false,error:'Account không tồn tại'});if(!channelId)return res.status(400).json({ok:false,error:'channelId là bắt buộc'});a.channels||=[];if(a.channels.some(c=>c.id===channelId))return res.status(409).json({ok:false,error:'Channel đã tồn tại'});a.channels.push({id:channelId,name:name||channelId});saveAccounts(d);res.status(201).json({ok:true,accounts:getPublicAccounts()})});
app.delete('/api/accounts/:id/channels/:channelId',(req,res)=>{const d=loadAccounts(),a=d.accounts.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({ok:false,error:'Account không tồn tại'});const n=a.channels?.length||0;a.channels=(a.channels||[]).filter(c=>c.id!==req.params.channelId);if(a.channels.length===n)return res.status(404).json({ok:false,error:'Channel không tồn tại'});saveAccounts(d);res.json({ok:true,accounts:getPublicAccounts()})});
app.post('/api/accounts/:id/active-channel',(req,res)=>{const{channelId}=req.body||{},d=loadAccounts(),a=d.accounts.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({ok:false,error:'Account không tồn tại'});if(!(a.channels||[]).some(c=>c.id===channelId))return res.status(404).json({ok:false,error:'Channel không tồn tại'});a.activeChannelId=channelId;saveAccounts(d);res.json({ok:true,accounts:getPublicAccounts()})});
app.post('/api/active-account',(req,res)=>{const{accountId}=req.body||{},d=loadAccounts();if(!d.accounts.some(a=>a.id===accountId))return res.status(404).json({ok:false,error:'Account không tồn tại'});d.activeAccountId=accountId;saveAccounts(d);res.json({ok:true,accounts:getPublicAccounts()})});

function splitMessages(text){return String(text||'').split(',').map(s=>s.trim()).filter(Boolean)}
function interval(body){const n=Number(body.intervalSeconds);if(!Number.isFinite(n)||n<1)throw new Error('Thời gian phải từ 1 giây');return Math.floor(n)}
app.post('/api/messages',(req,res)=>{try{const texts=splitMessages(req.body?.text);if(!texts.length)throw new Error('Tin nhắn không được để trống');const d=loadMessages(),base=String(req.body.id||'message');const sec=interval(req.body);const made=[];for(let i=0;i<texts.length;i++){let id=texts.length===1?base:`${base}-${i+1}`;while(d.messages.some(m=>m.id===id))id=`${base}-${Date.now()}-${i+1}`;const m={id,text:texts[i],intervalSeconds:sec,enabled:req.body.enabled!==false};d.messages.push(m);made.push(m)}if(!d.defaultMessage)d.defaultMessage=made[0].text;saveMessages(d);res.status(201).json({ok:true,added:made,messages:loadMessages()})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.put('/api/messages/:id',(req,res)=>{try{const d=loadMessages(),m=d.messages.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({ok:false,error:'Message không tồn tại'});const texts=splitMessages(req.body?.text);if(texts.length!==1)throw new Error('Khi sửa, chỉ nhập một tin nhắn; dùng Thêm để nhập nhiều tin bằng dấu phẩy');m.text=texts[0];m.intervalSeconds=interval(req.body);if(req.body.enabled!==undefined)m.enabled=Boolean(req.body.enabled);saveMessages(d);res.json({ok:true,messages:loadMessages()})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.delete('/api/messages/:id',(req,res)=>{const d=loadMessages(),n=d.messages.length;d.messages=d.messages.filter(m=>m.id!==req.params.id);if(d.messages.length===n)return res.status(404).json({ok:false,error:'Message không tồn tại'});if(!d.messages.length)d.defaultMessage='hello';else if(!d.messages.some(m=>m.text===d.defaultMessage))d.defaultMessage=d.messages[0].text;saveMessages(d);res.json({ok:true,messages:loadMessages()})});
app.post('/api/messages/default',(req,res)=>{const d=loadMessages(),m=d.messages.find(x=>x.id===req.body?.id);if(!m)return res.status(404).json({ok:false,error:'Message không tồn tại'});d.defaultMessage=m.text;saveMessages(d);res.json({ok:true,messages:loadMessages()})});
app.post('/api/ai/toggle',(req,res)=>{const enabled=Boolean(req.body?.enabled);aiListener.setEnabled(enabled);if(enabled)scheduler.stopCustomTimers();else scheduler.sync();res.json({ok:true,ai:aiListener.getStatus(),scheduler:scheduler.getStatus()})});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Kana local dashboard',port:config.server.port}));
function startDashboard(){app.listen(config.server.port,'127.0.0.1',()=>console.log(`[Dashboard] 🚀 http://127.0.0.1:${config.server.port}`))}
module.exports={startDashboard};
