const express = require('express');
const path = require('path');
const { loadAccounts, saveAccounts, loadMessages, saveMessages, getPublicAccounts, updateAccount, enableAccount } = require('./config-store');
const config = require('../config');
const { aiListener } = require('./ai/ai-listener');
const { verifyToken, sendMessage } = require('./discord');
const { scheduler } = require('./automation-core');
const { scanModels, scanOllamaModels } = require('./ai/ai-provider');
const ollama = require('./ai/ollama-manager');
const { loadAiSettings, saveAiSettings, getPublicAiSettings } = require('./ai/ai-settings-store');
const { loadMemory, clearMemory } = require('./memory-store');

const app = express();
app.use(express.json({ limit: '64kb' }));
app.get('/', (req, res) => res.sendFile(path.join(__dirname, '..', 'web', 'index.html')));
app.get('/api/config', (req, res) => res.json({...getPublicAccounts(),messages:loadMessages(),ai:{...aiListener.getStatus(),settings:getPublicAiSettings()},scheduler:scheduler.getStatus()}));
app.post('/api/ai/scan', async (req,res)=>{try{const apiKey=String(req.body?.apiKey||'').trim();if(!apiKey)throw new Error('API key không được để trống');const result=await scanModels(apiKey);const settings=saveAiSettings({apiKey,provider:result.provider.id,apiBase:result.provider.base,models:result.models,model:result.models.includes(loadAiSettings().model)?loadAiSettings().model:result.models[0]});res.json({ok:true,provider:result.provider,models:result.models,model:settings.model,ai:getPublicAiSettings()});}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/ollama/status',async(req,res)=>{try{res.json({ok:true,ollama:await ollama.status()})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/ollama/install',async(req,res)=>{try{const result=await ollama.install(line=>aiListener.log('INFO','Ollama install',{line}));res.json({ok:true,ollama:result})}catch(e){aiListener.log('ERROR','Ollama install failed',{error:e.message});res.status(400).json({ok:false,error:e.message})}});
app.post('/api/ollama/pull',async(req,res)=>{try{const model=String(req.body?.model||ollama.DEFAULT_MODEL).trim();const result=await ollama.pullModel(model,line=>aiListener.log('INFO','Ollama pull',{line}));saveAiSettings({ollamaModel:model});res.json({ok:true,ollama:result,ai:getPublicAiSettings()})}catch(e){aiListener.log('ERROR','Ollama pull failed',{error:e.message});res.status(400).json({ok:false,error:e.message})}});
app.post('/api/ollama/remove',async(req,res)=>{try{const result=await ollama.removeModel(String(req.body?.model||''),line=>aiListener.log('INFO','Ollama remove',{line}));res.json({ok:true,ollama:result})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/ollama/scan',async(req,res)=>{try{const result=await scanOllamaModels();res.json({ok:true,models:result.models,ollama:await ollama.status()})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/ai/model', (req,res)=>{try{const model=String(req.body?.model||'').trim(),s=loadAiSettings();if(!model||!s.models.includes(model))return res.status(400).json({ok:false,error:'Model không nằm trong danh sách đã scan'});saveAiSettings({model});res.json({ok:true,ai:getPublicAiSettings()});}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/ai/toggle',(req,res)=>{try{const enabled=Boolean(req.body?.enabled);aiListener.setEnabled(enabled);saveAiSettings({enabled});if(enabled)scheduler.stopCustomTimers();else scheduler.sync();res.json({ok:true,ai:{...aiListener.getStatus(),settings:getPublicAiSettings()},scheduler:scheduler.getStatus()});}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.get('/api/ai/memory/:accountId',(req,res)=>{try{res.json({ok:true,accountId:req.params.accountId,messages:loadMemory(req.params.accountId,100000)});}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.delete('/api/ai/memory/:accountId',(req,res)=>{try{clearMemory(req.params.accountId);res.json({ok:true});}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/ai/logs/clear',(req,res)=>{aiListener.clearLogs();res.json({ok:true});});

app.put('/api/accounts/:id',(req,res)=>{try{const account=updateAccount(req.params.id,req.body||{});if(!account)return res.status(404).json({ok:false,error:'Account không tồn tại'});res.json({ok:true,accounts:getPublicAccounts()})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/accounts/:id/verify',async(req,res)=>{const data=loadAccounts(),a=data.accounts.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({ok:false,error:'Account không tồn tại'});if(a.disabled)enableAccount(a.id);const target={accountId:a.id,accountName:a.name,token:a.token,channelId:(a.channels||[])[0]?.id};if(!target.token)return res.status(400).json({ok:false,error:'Account chưa có token'});const result=await verifyToken(target);res.status(result.ok?200:400).json({...result,accounts:getPublicAccounts()})});
app.post('/api/accounts',(req,res)=>{const{id,name,token}=req.body||{};if(!id||!name||!token)return res.status(400).json({ok:false,error:'id, name và token là bắt buộc'});const data=loadAccounts();if(data.accounts.some(a=>a.id===id))return res.status(409).json({ok:false,error:'Account ID đã tồn tại'});data.accounts.push({id,name,token,channels:[]});if(!data.activeAccountId)data.activeAccountId=id;saveAccounts(data);res.status(201).json({ok:true,accounts:getPublicAccounts()})});
app.delete('/api/accounts/:id',(req,res)=>{const d=loadAccounts(),n=d.accounts.length;d.accounts=d.accounts.filter(a=>a.id!==req.params.id);if(d.accounts.length===n)return res.status(404).json({ok:false,error:'Account không tồn tại'});if(d.activeAccountId===req.params.id)d.activeAccountId=d.accounts[0]?.id||null;saveAccounts(d);res.json({ok:true,accounts:getPublicAccounts()})});
app.post('/api/accounts/:id/channels',(req,res)=>{const{channelId,name}=req.body||{},d=loadAccounts(),a=d.accounts.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({ok:false,error:'Account không tồn tại'});if(!channelId)return res.status(400).json({ok:false,error:'channelId là bắt buộc'});a.channels||=[];if(a.channels.some(c=>c.id===channelId))return res.status(409).json({ok:false,error:'Channel đã tồn tại'});a.channels.push({id:channelId,name:name||channelId});saveAccounts(d);res.status(201).json({ok:true,accounts:getPublicAccounts()})});
app.delete('/api/accounts/:id/channels/:channelId',(req,res)=>{const d=loadAccounts(),a=d.accounts.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({ok:false,error:'Account không tồn tại'});const n=a.channels?.length||0;a.channels=(a.channels||[]).filter(c=>c.id!==req.params.channelId);if(a.channels.length===n)return res.status(404).json({ok:false,error:'Channel không tồn tại'});saveAccounts(d);res.json({ok:true,accounts:getPublicAccounts()})});
app.post('/api/accounts/:id/active-channel',(req,res)=>{const{channelId}=req.body||{},d=loadAccounts(),a=d.accounts.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({ok:false,error:'Account không tồn tại'});if(!(a.channels||[]).some(c=>c.id===channelId))return res.status(404).json({ok:false,error:'Channel không tồn tại'});a.activeChannelId=channelId;saveAccounts(d);res.json({ok:true,accounts:getPublicAccounts()})});
app.post('/api/active-account',(req,res)=>{const{accountId}=req.body||{},d=loadAccounts();if(!d.accounts.some(a=>a.id===accountId))return res.status(404).json({ok:false,error:'Account không tồn tại'});d.activeAccountId=accountId;saveAccounts(d);res.json({ok:true,accounts:getPublicAccounts()})});

function splitMessages(text){return String(text||'').split(',').map(s=>s.trim()).filter(Boolean)}
function interval(body){const n=Number(body.intervalSeconds);if(!Number.isFinite(n)||n<1)throw new Error('Thời gian phải từ 1 giây');return Math.floor(n)}
app.post('/api/messages',(req,res)=>{try{const texts=splitMessages(req.body?.text);if(!texts.length)throw new Error('Tin nhắn không được để trống');const d=loadMessages(),base=String(req.body.id||'message');const sec=interval(req.body);const made=[];for(let i=0;i<texts.length;i++){let id=texts.length===1?base:`${base}-${i+1}`;while(d.messages.some(m=>m.id===id))id=`${base}-${Date.now()}-${i+1}`;const m={id,text:texts[i],intervalSeconds:sec,enabled:req.body.enabled!==false};d.messages.push(m);made.push(m)}if(!d.defaultMessage)d.defaultMessage=made[0].text;saveMessages(d);res.status(201).json({ok:true,added:made,messages:loadMessages()})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.put('/api/messages/:id',(req,res)=>{try{const d=loadMessages(),m=d.messages.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({ok:false,error:'Message không tồn tại'});const texts=splitMessages(req.body?.text);if(texts.length!==1)throw new Error('Khi sửa, chỉ nhập một tin nhắn; dùng Thêm để nhập nhiều tin bằng dấu phẩy');m.text=texts[0];m.intervalSeconds=interval(req.body);if(req.body.enabled!==undefined)m.enabled=Boolean(req.body.enabled);saveMessages(d);res.json({ok:true,messages:loadMessages()})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.delete('/api/messages/:id',(req,res)=>{const d=loadMessages(),n=d.messages.length;d.messages=d.messages.filter(m=>m.id!==req.params.id);if(d.messages.length===n)return res.status(404).json({ok:false,error:'Message không tồn tại'});if(!d.messages.length)d.defaultMessage='hello';else if(!d.messages.some(m=>m.text===d.defaultMessage))d.defaultMessage=d.messages[0].text;saveMessages(d);res.json({ok:true,messages:loadMessages()})});
app.post('/api/messages/send-now',(req,res)=>{const d=loadMessages(),m=d.messages.find(x=>x.id===req.body?.id);if(!m)return res.status(404).json({ok:false,error:'Message không tồn tại'});if(aiListener.enabled)return res.status(409).json({ok:false,error:'AI Reply đang bật'});sendMessage(m.text).then(result=>res.status(result.ok?200:400).json(result)).catch(e=>res.status(500).json({ok:false,error:e.message}))});
app.post('/api/messages/toggle',(req,res)=>{const d=loadMessages(),m=d.messages.find(x=>x.id===req.body?.id);if(!m)return res.status(404).json({ok:false,error:'Message không tồn tại'});m.enabled=Boolean(req.body.enabled);saveMessages(d);scheduler.sync();res.json({ok:true,messages:loadMessages(),scheduler:scheduler.getStatus()})});
app.post('/api/messages/default',(req,res)=>{const d=loadMessages(),m=d.messages.find(x=>x.id===req.body?.id);if(!m)return res.status(404).json({ok:false,error:'Message không tồn tại'});d.defaultMessage=m.text;saveMessages(d);res.json({ok:true,messages:loadMessages()})});

app.get('/api/health',(req,res)=>res.json({ok:true,service:'Kana local dashboard',port:config.server.port}));
function startDashboard(){app.listen(config.server.port,'127.0.0.1',()=>console.log(`[Dashboard] 🚀 http://127.0.0.1:${config.server.port}`))}
module.exports={startDashboard};
